### ISSUE TITLE
New Function Optimizer Proposal

### ISSUE THREAD

**Issue by avaneev** [jppbsi/LibOPT-plus#2]
I've created a new stochastic function optimizer which you may be interested in evaluating. It's written in C++, but interfacing with it should not be hard. What I'm interested in is hearing your opinion, based on your benchmarking routine. I'm using a slightly different test function set, and the optimizer solves most problems given at least 50 optimization attempts are performed, up to 2000 iterations each.

Of course, you may include it into your project if you find it interesting.

https://github.com/avaneev/biteopt

**Comment by gugarosa** [comment]
Hello Aleksey! It is a really nice project indeed, we will definitely take a further look onto it and try to understand what it does. Meanwhile, do you have the source paper from where you implemented the algorithm, so it would easier our lifes in trying to understand the math behind it?

Thank you for your attention!

**Comment by avaneev** [comment]
Thanks for your interest. This is a completely original work, I do not have a dedicated paper - but the algorithm is described in the source "bitefan.h" file.

**Comment by jppbsi** [comment]
Thank you, Aleksey! We are now in a process of studying and including new techniques. Usually, we include only techniques that have been published elsewhere. But we are working on it, anyway.  Best,

**Comment by avaneev** [comment]
As I'm not associated with any academic institution, I have no plans to produce a paper even if this algorithm is worth it. Beside that, the analysis of this strategy is complicated due to its probabilistic nature.

**Comment by jppbsi** [comment]
Thanks for letting us know. Aleksey. We keep in touch. Best,

**Comment by avaneev** [comment]
It would be interesting to know which test functions this optimizer fails to optimize in 50 attempts - if you have an automated benchmark that can print that information. I would like to add them to my still small list of unsolvable functions, to possibly improve algorithm in the future.

**Comment by jppbsi** [comment]
Yes, that would be nice. If you implement your technique on LibOPT, you can make use of all functions implemented there (more than 100). Best,

**Comment by avaneev** [comment]
Well, I do not understand your library like you do. Maybe you can include it yourself. The source code is free, under MIT license.

**Comment by gugarosa** [comment]
Please refer to the wiki in order to know how to work with the library, i.e., https://github.com/jppbsi/LibOPT/wiki
