### ISSUE TITLE
Broken link to install gcc on OSX

### ISSUE THREAD

**Issue by lzfelix** [jppbsi/LibOPT-plus#7]
Not anything serious, but the link to the tutorial on how to install gcc under OSX in the [Installation page from the wiki](https://github.com/jppbsi/LibOPT/wiki/Installation) is broken.

**Comment by recogna** [comment]
Thanks, @lzfelix We've removed that phrase since that tip might be outdated due to the recent versions of OSX.

**Comment by lzfelix** [comment]
I think that installing gcc for recent OSX versions is not necessary anymore, since I had no issues compilling LibOPT with `Apple LLVM version 10.0.0 (clang-1000.10.44.4)`.
